baseURL = 'https://paulgmiller.github.io'
languageCode = 'en-us'
title = 'The gyrations of a pointless and uncaring universe'

[author]
  name = 'Paul Miller'
  email = 'paul.miller@gmail.com'

[params]
  giturl = 'https://github.com/paulgmiller/paulgmiller.github.io'

[outputs]
  home = ['HTML', 'RSS']

[outputFormats.RSS]
  mediaType = 'application/rss+xml'
  baseName = 'rss'

[markup.goldmark.renderer]
  unsafe = true

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

ignoreLogs = ['warning-goldmark-raw-html']
